# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/eblackbu/ft_ls

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/eblackbu/ft_ls

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eblackbu/ft_ls/CMakeFiles /Users/eblackbu/ft_ls/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eblackbu/ft_ls/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft_ls

# Build rule for target.
ft_ls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ft_ls
.PHONY : ft_ls

# fast build rule for target.
ft_ls/fast:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/build
.PHONY : ft_ls/fast

acrights_helper.o: acrights_helper.c.o

.PHONY : acrights_helper.o

# target to build an object file
acrights_helper.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/acrights_helper.c.o
.PHONY : acrights_helper.c.o

acrights_helper.i: acrights_helper.c.i

.PHONY : acrights_helper.i

# target to preprocess a source file
acrights_helper.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/acrights_helper.c.i
.PHONY : acrights_helper.c.i

acrights_helper.s: acrights_helper.c.s

.PHONY : acrights_helper.s

# target to generate assembly for a file
acrights_helper.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/acrights_helper.c.s
.PHONY : acrights_helper.c.s

arg_parser.o: arg_parser.c.o

.PHONY : arg_parser.o

# target to build an object file
arg_parser.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/arg_parser.c.o
.PHONY : arg_parser.c.o

arg_parser.i: arg_parser.c.i

.PHONY : arg_parser.i

# target to preprocess a source file
arg_parser.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/arg_parser.c.i
.PHONY : arg_parser.c.i

arg_parser.s: arg_parser.c.s

.PHONY : arg_parser.s

# target to generate assembly for a file
arg_parser.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/arg_parser.c.s
.PHONY : arg_parser.c.s

comparators.o: comparators.c.o

.PHONY : comparators.o

# target to build an object file
comparators.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/comparators.c.o
.PHONY : comparators.c.o

comparators.i: comparators.c.i

.PHONY : comparators.i

# target to preprocess a source file
comparators.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/comparators.c.i
.PHONY : comparators.c.i

comparators.s: comparators.c.s

.PHONY : comparators.s

# target to generate assembly for a file
comparators.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/comparators.c.s
.PHONY : comparators.c.s

comparators_2.o: comparators_2.c.o

.PHONY : comparators_2.o

# target to build an object file
comparators_2.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/comparators_2.c.o
.PHONY : comparators_2.c.o

comparators_2.i: comparators_2.c.i

.PHONY : comparators_2.i

# target to preprocess a source file
comparators_2.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/comparators_2.c.i
.PHONY : comparators_2.c.i

comparators_2.s: comparators_2.c.s

.PHONY : comparators_2.s

# target to generate assembly for a file
comparators_2.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/comparators_2.c.s
.PHONY : comparators_2.c.s

del_from_lists.o: del_from_lists.c.o

.PHONY : del_from_lists.o

# target to build an object file
del_from_lists.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/del_from_lists.c.o
.PHONY : del_from_lists.c.o

del_from_lists.i: del_from_lists.c.i

.PHONY : del_from_lists.i

# target to preprocess a source file
del_from_lists.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/del_from_lists.c.i
.PHONY : del_from_lists.c.i

del_from_lists.s: del_from_lists.c.s

.PHONY : del_from_lists.s

# target to generate assembly for a file
del_from_lists.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/del_from_lists.c.s
.PHONY : del_from_lists.c.s

errors.o: errors.c.o

.PHONY : errors.o

# target to build an object file
errors.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/errors.c.o
.PHONY : errors.c.o

errors.i: errors.c.i

.PHONY : errors.i

# target to preprocess a source file
errors.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/errors.c.i
.PHONY : errors.c.i

errors.s: errors.c.s

.PHONY : errors.s

# target to generate assembly for a file
errors.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/errors.c.s
.PHONY : errors.c.s

get_fileinfo_1.o: get_fileinfo_1.c.o

.PHONY : get_fileinfo_1.o

# target to build an object file
get_fileinfo_1.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/get_fileinfo_1.c.o
.PHONY : get_fileinfo_1.c.o

get_fileinfo_1.i: get_fileinfo_1.c.i

.PHONY : get_fileinfo_1.i

# target to preprocess a source file
get_fileinfo_1.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/get_fileinfo_1.c.i
.PHONY : get_fileinfo_1.c.i

get_fileinfo_1.s: get_fileinfo_1.c.s

.PHONY : get_fileinfo_1.s

# target to generate assembly for a file
get_fileinfo_1.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/get_fileinfo_1.c.s
.PHONY : get_fileinfo_1.c.s

get_fileinfo_2.o: get_fileinfo_2.c.o

.PHONY : get_fileinfo_2.o

# target to build an object file
get_fileinfo_2.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/get_fileinfo_2.c.o
.PHONY : get_fileinfo_2.c.o

get_fileinfo_2.i: get_fileinfo_2.c.i

.PHONY : get_fileinfo_2.i

# target to preprocess a source file
get_fileinfo_2.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/get_fileinfo_2.c.i
.PHONY : get_fileinfo_2.c.i

get_fileinfo_2.s: get_fileinfo_2.c.s

.PHONY : get_fileinfo_2.s

# target to generate assembly for a file
get_fileinfo_2.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/get_fileinfo_2.c.s
.PHONY : get_fileinfo_2.c.s

l_flag_helper1.o: l_flag_helper1.c.o

.PHONY : l_flag_helper1.o

# target to build an object file
l_flag_helper1.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/l_flag_helper1.c.o
.PHONY : l_flag_helper1.c.o

l_flag_helper1.i: l_flag_helper1.c.i

.PHONY : l_flag_helper1.i

# target to preprocess a source file
l_flag_helper1.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/l_flag_helper1.c.i
.PHONY : l_flag_helper1.c.i

l_flag_helper1.s: l_flag_helper1.c.s

.PHONY : l_flag_helper1.s

# target to generate assembly for a file
l_flag_helper1.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/l_flag_helper1.c.s
.PHONY : l_flag_helper1.c.s

libft/ft_atoi.o: libft/ft_atoi.c.o

.PHONY : libft/ft_atoi.o

# target to build an object file
libft/ft_atoi.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_atoi.c.o
.PHONY : libft/ft_atoi.c.o

libft/ft_atoi.i: libft/ft_atoi.c.i

.PHONY : libft/ft_atoi.i

# target to preprocess a source file
libft/ft_atoi.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_atoi.c.i
.PHONY : libft/ft_atoi.c.i

libft/ft_atoi.s: libft/ft_atoi.c.s

.PHONY : libft/ft_atoi.s

# target to generate assembly for a file
libft/ft_atoi.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_atoi.c.s
.PHONY : libft/ft_atoi.c.s

libft/ft_bzero.o: libft/ft_bzero.c.o

.PHONY : libft/ft_bzero.o

# target to build an object file
libft/ft_bzero.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_bzero.c.o
.PHONY : libft/ft_bzero.c.o

libft/ft_bzero.i: libft/ft_bzero.c.i

.PHONY : libft/ft_bzero.i

# target to preprocess a source file
libft/ft_bzero.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_bzero.c.i
.PHONY : libft/ft_bzero.c.i

libft/ft_bzero.s: libft/ft_bzero.c.s

.PHONY : libft/ft_bzero.s

# target to generate assembly for a file
libft/ft_bzero.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_bzero.c.s
.PHONY : libft/ft_bzero.c.s

libft/ft_isalnum.o: libft/ft_isalnum.c.o

.PHONY : libft/ft_isalnum.o

# target to build an object file
libft/ft_isalnum.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isalnum.c.o
.PHONY : libft/ft_isalnum.c.o

libft/ft_isalnum.i: libft/ft_isalnum.c.i

.PHONY : libft/ft_isalnum.i

# target to preprocess a source file
libft/ft_isalnum.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isalnum.c.i
.PHONY : libft/ft_isalnum.c.i

libft/ft_isalnum.s: libft/ft_isalnum.c.s

.PHONY : libft/ft_isalnum.s

# target to generate assembly for a file
libft/ft_isalnum.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isalnum.c.s
.PHONY : libft/ft_isalnum.c.s

libft/ft_isalpha.o: libft/ft_isalpha.c.o

.PHONY : libft/ft_isalpha.o

# target to build an object file
libft/ft_isalpha.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isalpha.c.o
.PHONY : libft/ft_isalpha.c.o

libft/ft_isalpha.i: libft/ft_isalpha.c.i

.PHONY : libft/ft_isalpha.i

# target to preprocess a source file
libft/ft_isalpha.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isalpha.c.i
.PHONY : libft/ft_isalpha.c.i

libft/ft_isalpha.s: libft/ft_isalpha.c.s

.PHONY : libft/ft_isalpha.s

# target to generate assembly for a file
libft/ft_isalpha.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isalpha.c.s
.PHONY : libft/ft_isalpha.c.s

libft/ft_isascii.o: libft/ft_isascii.c.o

.PHONY : libft/ft_isascii.o

# target to build an object file
libft/ft_isascii.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isascii.c.o
.PHONY : libft/ft_isascii.c.o

libft/ft_isascii.i: libft/ft_isascii.c.i

.PHONY : libft/ft_isascii.i

# target to preprocess a source file
libft/ft_isascii.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isascii.c.i
.PHONY : libft/ft_isascii.c.i

libft/ft_isascii.s: libft/ft_isascii.c.s

.PHONY : libft/ft_isascii.s

# target to generate assembly for a file
libft/ft_isascii.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isascii.c.s
.PHONY : libft/ft_isascii.c.s

libft/ft_isdigit.o: libft/ft_isdigit.c.o

.PHONY : libft/ft_isdigit.o

# target to build an object file
libft/ft_isdigit.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isdigit.c.o
.PHONY : libft/ft_isdigit.c.o

libft/ft_isdigit.i: libft/ft_isdigit.c.i

.PHONY : libft/ft_isdigit.i

# target to preprocess a source file
libft/ft_isdigit.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isdigit.c.i
.PHONY : libft/ft_isdigit.c.i

libft/ft_isdigit.s: libft/ft_isdigit.c.s

.PHONY : libft/ft_isdigit.s

# target to generate assembly for a file
libft/ft_isdigit.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isdigit.c.s
.PHONY : libft/ft_isdigit.c.s

libft/ft_isprint.o: libft/ft_isprint.c.o

.PHONY : libft/ft_isprint.o

# target to build an object file
libft/ft_isprint.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isprint.c.o
.PHONY : libft/ft_isprint.c.o

libft/ft_isprint.i: libft/ft_isprint.c.i

.PHONY : libft/ft_isprint.i

# target to preprocess a source file
libft/ft_isprint.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isprint.c.i
.PHONY : libft/ft_isprint.c.i

libft/ft_isprint.s: libft/ft_isprint.c.s

.PHONY : libft/ft_isprint.s

# target to generate assembly for a file
libft/ft_isprint.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isprint.c.s
.PHONY : libft/ft_isprint.c.s

libft/ft_isspace.o: libft/ft_isspace.c.o

.PHONY : libft/ft_isspace.o

# target to build an object file
libft/ft_isspace.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isspace.c.o
.PHONY : libft/ft_isspace.c.o

libft/ft_isspace.i: libft/ft_isspace.c.i

.PHONY : libft/ft_isspace.i

# target to preprocess a source file
libft/ft_isspace.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isspace.c.i
.PHONY : libft/ft_isspace.c.i

libft/ft_isspace.s: libft/ft_isspace.c.s

.PHONY : libft/ft_isspace.s

# target to generate assembly for a file
libft/ft_isspace.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_isspace.c.s
.PHONY : libft/ft_isspace.c.s

libft/ft_itoa.o: libft/ft_itoa.c.o

.PHONY : libft/ft_itoa.o

# target to build an object file
libft/ft_itoa.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_itoa.c.o
.PHONY : libft/ft_itoa.c.o

libft/ft_itoa.i: libft/ft_itoa.c.i

.PHONY : libft/ft_itoa.i

# target to preprocess a source file
libft/ft_itoa.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_itoa.c.i
.PHONY : libft/ft_itoa.c.i

libft/ft_itoa.s: libft/ft_itoa.c.s

.PHONY : libft/ft_itoa.s

# target to generate assembly for a file
libft/ft_itoa.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_itoa.c.s
.PHONY : libft/ft_itoa.c.s

libft/ft_lstadd.o: libft/ft_lstadd.c.o

.PHONY : libft/ft_lstadd.o

# target to build an object file
libft/ft_lstadd.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstadd.c.o
.PHONY : libft/ft_lstadd.c.o

libft/ft_lstadd.i: libft/ft_lstadd.c.i

.PHONY : libft/ft_lstadd.i

# target to preprocess a source file
libft/ft_lstadd.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstadd.c.i
.PHONY : libft/ft_lstadd.c.i

libft/ft_lstadd.s: libft/ft_lstadd.c.s

.PHONY : libft/ft_lstadd.s

# target to generate assembly for a file
libft/ft_lstadd.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstadd.c.s
.PHONY : libft/ft_lstadd.c.s

libft/ft_lstdel.o: libft/ft_lstdel.c.o

.PHONY : libft/ft_lstdel.o

# target to build an object file
libft/ft_lstdel.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstdel.c.o
.PHONY : libft/ft_lstdel.c.o

libft/ft_lstdel.i: libft/ft_lstdel.c.i

.PHONY : libft/ft_lstdel.i

# target to preprocess a source file
libft/ft_lstdel.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstdel.c.i
.PHONY : libft/ft_lstdel.c.i

libft/ft_lstdel.s: libft/ft_lstdel.c.s

.PHONY : libft/ft_lstdel.s

# target to generate assembly for a file
libft/ft_lstdel.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstdel.c.s
.PHONY : libft/ft_lstdel.c.s

libft/ft_lstdelone.o: libft/ft_lstdelone.c.o

.PHONY : libft/ft_lstdelone.o

# target to build an object file
libft/ft_lstdelone.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstdelone.c.o
.PHONY : libft/ft_lstdelone.c.o

libft/ft_lstdelone.i: libft/ft_lstdelone.c.i

.PHONY : libft/ft_lstdelone.i

# target to preprocess a source file
libft/ft_lstdelone.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstdelone.c.i
.PHONY : libft/ft_lstdelone.c.i

libft/ft_lstdelone.s: libft/ft_lstdelone.c.s

.PHONY : libft/ft_lstdelone.s

# target to generate assembly for a file
libft/ft_lstdelone.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstdelone.c.s
.PHONY : libft/ft_lstdelone.c.s

libft/ft_lstiter.o: libft/ft_lstiter.c.o

.PHONY : libft/ft_lstiter.o

# target to build an object file
libft/ft_lstiter.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstiter.c.o
.PHONY : libft/ft_lstiter.c.o

libft/ft_lstiter.i: libft/ft_lstiter.c.i

.PHONY : libft/ft_lstiter.i

# target to preprocess a source file
libft/ft_lstiter.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstiter.c.i
.PHONY : libft/ft_lstiter.c.i

libft/ft_lstiter.s: libft/ft_lstiter.c.s

.PHONY : libft/ft_lstiter.s

# target to generate assembly for a file
libft/ft_lstiter.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstiter.c.s
.PHONY : libft/ft_lstiter.c.s

libft/ft_lstmap.o: libft/ft_lstmap.c.o

.PHONY : libft/ft_lstmap.o

# target to build an object file
libft/ft_lstmap.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstmap.c.o
.PHONY : libft/ft_lstmap.c.o

libft/ft_lstmap.i: libft/ft_lstmap.c.i

.PHONY : libft/ft_lstmap.i

# target to preprocess a source file
libft/ft_lstmap.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstmap.c.i
.PHONY : libft/ft_lstmap.c.i

libft/ft_lstmap.s: libft/ft_lstmap.c.s

.PHONY : libft/ft_lstmap.s

# target to generate assembly for a file
libft/ft_lstmap.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstmap.c.s
.PHONY : libft/ft_lstmap.c.s

libft/ft_lstnew.o: libft/ft_lstnew.c.o

.PHONY : libft/ft_lstnew.o

# target to build an object file
libft/ft_lstnew.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstnew.c.o
.PHONY : libft/ft_lstnew.c.o

libft/ft_lstnew.i: libft/ft_lstnew.c.i

.PHONY : libft/ft_lstnew.i

# target to preprocess a source file
libft/ft_lstnew.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstnew.c.i
.PHONY : libft/ft_lstnew.c.i

libft/ft_lstnew.s: libft/ft_lstnew.c.s

.PHONY : libft/ft_lstnew.s

# target to generate assembly for a file
libft/ft_lstnew.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_lstnew.c.s
.PHONY : libft/ft_lstnew.c.s

libft/ft_memalloc.o: libft/ft_memalloc.c.o

.PHONY : libft/ft_memalloc.o

# target to build an object file
libft/ft_memalloc.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memalloc.c.o
.PHONY : libft/ft_memalloc.c.o

libft/ft_memalloc.i: libft/ft_memalloc.c.i

.PHONY : libft/ft_memalloc.i

# target to preprocess a source file
libft/ft_memalloc.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memalloc.c.i
.PHONY : libft/ft_memalloc.c.i

libft/ft_memalloc.s: libft/ft_memalloc.c.s

.PHONY : libft/ft_memalloc.s

# target to generate assembly for a file
libft/ft_memalloc.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memalloc.c.s
.PHONY : libft/ft_memalloc.c.s

libft/ft_memccpy.o: libft/ft_memccpy.c.o

.PHONY : libft/ft_memccpy.o

# target to build an object file
libft/ft_memccpy.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memccpy.c.o
.PHONY : libft/ft_memccpy.c.o

libft/ft_memccpy.i: libft/ft_memccpy.c.i

.PHONY : libft/ft_memccpy.i

# target to preprocess a source file
libft/ft_memccpy.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memccpy.c.i
.PHONY : libft/ft_memccpy.c.i

libft/ft_memccpy.s: libft/ft_memccpy.c.s

.PHONY : libft/ft_memccpy.s

# target to generate assembly for a file
libft/ft_memccpy.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memccpy.c.s
.PHONY : libft/ft_memccpy.c.s

libft/ft_memchr.o: libft/ft_memchr.c.o

.PHONY : libft/ft_memchr.o

# target to build an object file
libft/ft_memchr.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memchr.c.o
.PHONY : libft/ft_memchr.c.o

libft/ft_memchr.i: libft/ft_memchr.c.i

.PHONY : libft/ft_memchr.i

# target to preprocess a source file
libft/ft_memchr.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memchr.c.i
.PHONY : libft/ft_memchr.c.i

libft/ft_memchr.s: libft/ft_memchr.c.s

.PHONY : libft/ft_memchr.s

# target to generate assembly for a file
libft/ft_memchr.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memchr.c.s
.PHONY : libft/ft_memchr.c.s

libft/ft_memcmp.o: libft/ft_memcmp.c.o

.PHONY : libft/ft_memcmp.o

# target to build an object file
libft/ft_memcmp.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memcmp.c.o
.PHONY : libft/ft_memcmp.c.o

libft/ft_memcmp.i: libft/ft_memcmp.c.i

.PHONY : libft/ft_memcmp.i

# target to preprocess a source file
libft/ft_memcmp.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memcmp.c.i
.PHONY : libft/ft_memcmp.c.i

libft/ft_memcmp.s: libft/ft_memcmp.c.s

.PHONY : libft/ft_memcmp.s

# target to generate assembly for a file
libft/ft_memcmp.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memcmp.c.s
.PHONY : libft/ft_memcmp.c.s

libft/ft_memcpy.o: libft/ft_memcpy.c.o

.PHONY : libft/ft_memcpy.o

# target to build an object file
libft/ft_memcpy.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memcpy.c.o
.PHONY : libft/ft_memcpy.c.o

libft/ft_memcpy.i: libft/ft_memcpy.c.i

.PHONY : libft/ft_memcpy.i

# target to preprocess a source file
libft/ft_memcpy.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memcpy.c.i
.PHONY : libft/ft_memcpy.c.i

libft/ft_memcpy.s: libft/ft_memcpy.c.s

.PHONY : libft/ft_memcpy.s

# target to generate assembly for a file
libft/ft_memcpy.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memcpy.c.s
.PHONY : libft/ft_memcpy.c.s

libft/ft_memdel.o: libft/ft_memdel.c.o

.PHONY : libft/ft_memdel.o

# target to build an object file
libft/ft_memdel.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memdel.c.o
.PHONY : libft/ft_memdel.c.o

libft/ft_memdel.i: libft/ft_memdel.c.i

.PHONY : libft/ft_memdel.i

# target to preprocess a source file
libft/ft_memdel.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memdel.c.i
.PHONY : libft/ft_memdel.c.i

libft/ft_memdel.s: libft/ft_memdel.c.s

.PHONY : libft/ft_memdel.s

# target to generate assembly for a file
libft/ft_memdel.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memdel.c.s
.PHONY : libft/ft_memdel.c.s

libft/ft_memmove.o: libft/ft_memmove.c.o

.PHONY : libft/ft_memmove.o

# target to build an object file
libft/ft_memmove.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memmove.c.o
.PHONY : libft/ft_memmove.c.o

libft/ft_memmove.i: libft/ft_memmove.c.i

.PHONY : libft/ft_memmove.i

# target to preprocess a source file
libft/ft_memmove.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memmove.c.i
.PHONY : libft/ft_memmove.c.i

libft/ft_memmove.s: libft/ft_memmove.c.s

.PHONY : libft/ft_memmove.s

# target to generate assembly for a file
libft/ft_memmove.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memmove.c.s
.PHONY : libft/ft_memmove.c.s

libft/ft_memset.o: libft/ft_memset.c.o

.PHONY : libft/ft_memset.o

# target to build an object file
libft/ft_memset.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memset.c.o
.PHONY : libft/ft_memset.c.o

libft/ft_memset.i: libft/ft_memset.c.i

.PHONY : libft/ft_memset.i

# target to preprocess a source file
libft/ft_memset.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memset.c.i
.PHONY : libft/ft_memset.c.i

libft/ft_memset.s: libft/ft_memset.c.s

.PHONY : libft/ft_memset.s

# target to generate assembly for a file
libft/ft_memset.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_memset.c.s
.PHONY : libft/ft_memset.c.s

libft/ft_printf/colored.o: libft/ft_printf/colored.c.o

.PHONY : libft/ft_printf/colored.o

# target to build an object file
libft/ft_printf/colored.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/colored.c.o
.PHONY : libft/ft_printf/colored.c.o

libft/ft_printf/colored.i: libft/ft_printf/colored.c.i

.PHONY : libft/ft_printf/colored.i

# target to preprocess a source file
libft/ft_printf/colored.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/colored.c.i
.PHONY : libft/ft_printf/colored.c.i

libft/ft_printf/colored.s: libft/ft_printf/colored.c.s

.PHONY : libft/ft_printf/colored.s

# target to generate assembly for a file
libft/ft_printf/colored.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/colored.c.s
.PHONY : libft/ft_printf/colored.c.s

libft/ft_printf/ft_itoa_base.o: libft/ft_printf/ft_itoa_base.c.o

.PHONY : libft/ft_printf/ft_itoa_base.o

# target to build an object file
libft/ft_printf/ft_itoa_base.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/ft_itoa_base.c.o
.PHONY : libft/ft_printf/ft_itoa_base.c.o

libft/ft_printf/ft_itoa_base.i: libft/ft_printf/ft_itoa_base.c.i

.PHONY : libft/ft_printf/ft_itoa_base.i

# target to preprocess a source file
libft/ft_printf/ft_itoa_base.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/ft_itoa_base.c.i
.PHONY : libft/ft_printf/ft_itoa_base.c.i

libft/ft_printf/ft_itoa_base.s: libft/ft_printf/ft_itoa_base.c.s

.PHONY : libft/ft_printf/ft_itoa_base.s

# target to generate assembly for a file
libft/ft_printf/ft_itoa_base.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/ft_itoa_base.c.s
.PHONY : libft/ft_printf/ft_itoa_base.c.s

libft/ft_printf/ft_itoa_base_uns.o: libft/ft_printf/ft_itoa_base_uns.c.o

.PHONY : libft/ft_printf/ft_itoa_base_uns.o

# target to build an object file
libft/ft_printf/ft_itoa_base_uns.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/ft_itoa_base_uns.c.o
.PHONY : libft/ft_printf/ft_itoa_base_uns.c.o

libft/ft_printf/ft_itoa_base_uns.i: libft/ft_printf/ft_itoa_base_uns.c.i

.PHONY : libft/ft_printf/ft_itoa_base_uns.i

# target to preprocess a source file
libft/ft_printf/ft_itoa_base_uns.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/ft_itoa_base_uns.c.i
.PHONY : libft/ft_printf/ft_itoa_base_uns.c.i

libft/ft_printf/ft_itoa_base_uns.s: libft/ft_printf/ft_itoa_base_uns.c.s

.PHONY : libft/ft_printf/ft_itoa_base_uns.s

# target to generate assembly for a file
libft/ft_printf/ft_itoa_base_uns.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/ft_itoa_base_uns.c.s
.PHONY : libft/ft_printf/ft_itoa_base_uns.c.s

libft/ft_printf/ft_printf.o: libft/ft_printf/ft_printf.c.o

.PHONY : libft/ft_printf/ft_printf.o

# target to build an object file
libft/ft_printf/ft_printf.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/ft_printf.c.o
.PHONY : libft/ft_printf/ft_printf.c.o

libft/ft_printf/ft_printf.i: libft/ft_printf/ft_printf.c.i

.PHONY : libft/ft_printf/ft_printf.i

# target to preprocess a source file
libft/ft_printf/ft_printf.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/ft_printf.c.i
.PHONY : libft/ft_printf/ft_printf.c.i

libft/ft_printf/ft_printf.s: libft/ft_printf/ft_printf.c.s

.PHONY : libft/ft_printf/ft_printf.s

# target to generate assembly for a file
libft/ft_printf/ft_printf.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/ft_printf.c.s
.PHONY : libft/ft_printf/ft_printf.c.s

libft/ft_printf/get_format.o: libft/ft_printf/get_format.c.o

.PHONY : libft/ft_printf/get_format.o

# target to build an object file
libft/ft_printf/get_format.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/get_format.c.o
.PHONY : libft/ft_printf/get_format.c.o

libft/ft_printf/get_format.i: libft/ft_printf/get_format.c.i

.PHONY : libft/ft_printf/get_format.i

# target to preprocess a source file
libft/ft_printf/get_format.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/get_format.c.i
.PHONY : libft/ft_printf/get_format.c.i

libft/ft_printf/get_format.s: libft/ft_printf/get_format.c.s

.PHONY : libft/ft_printf/get_format.s

# target to generate assembly for a file
libft/ft_printf/get_format.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/get_format.c.s
.PHONY : libft/ft_printf/get_format.c.s

libft/ft_printf/helper_numbers.o: libft/ft_printf/helper_numbers.c.o

.PHONY : libft/ft_printf/helper_numbers.o

# target to build an object file
libft/ft_printf/helper_numbers.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/helper_numbers.c.o
.PHONY : libft/ft_printf/helper_numbers.c.o

libft/ft_printf/helper_numbers.i: libft/ft_printf/helper_numbers.c.i

.PHONY : libft/ft_printf/helper_numbers.i

# target to preprocess a source file
libft/ft_printf/helper_numbers.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/helper_numbers.c.i
.PHONY : libft/ft_printf/helper_numbers.c.i

libft/ft_printf/helper_numbers.s: libft/ft_printf/helper_numbers.c.s

.PHONY : libft/ft_printf/helper_numbers.s

# target to generate assembly for a file
libft/ft_printf/helper_numbers.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/helper_numbers.c.s
.PHONY : libft/ft_printf/helper_numbers.c.s

libft/ft_printf/helper_numbers2.o: libft/ft_printf/helper_numbers2.c.o

.PHONY : libft/ft_printf/helper_numbers2.o

# target to build an object file
libft/ft_printf/helper_numbers2.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/helper_numbers2.c.o
.PHONY : libft/ft_printf/helper_numbers2.c.o

libft/ft_printf/helper_numbers2.i: libft/ft_printf/helper_numbers2.c.i

.PHONY : libft/ft_printf/helper_numbers2.i

# target to preprocess a source file
libft/ft_printf/helper_numbers2.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/helper_numbers2.c.i
.PHONY : libft/ft_printf/helper_numbers2.c.i

libft/ft_printf/helper_numbers2.s: libft/ft_printf/helper_numbers2.c.s

.PHONY : libft/ft_printf/helper_numbers2.s

# target to generate assembly for a file
libft/ft_printf/helper_numbers2.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/helper_numbers2.c.s
.PHONY : libft/ft_printf/helper_numbers2.c.s

libft/ft_printf/print_addr_helper.o: libft/ft_printf/print_addr_helper.c.o

.PHONY : libft/ft_printf/print_addr_helper.o

# target to build an object file
libft/ft_printf/print_addr_helper.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_addr_helper.c.o
.PHONY : libft/ft_printf/print_addr_helper.c.o

libft/ft_printf/print_addr_helper.i: libft/ft_printf/print_addr_helper.c.i

.PHONY : libft/ft_printf/print_addr_helper.i

# target to preprocess a source file
libft/ft_printf/print_addr_helper.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_addr_helper.c.i
.PHONY : libft/ft_printf/print_addr_helper.c.i

libft/ft_printf/print_addr_helper.s: libft/ft_printf/print_addr_helper.c.s

.PHONY : libft/ft_printf/print_addr_helper.s

# target to generate assembly for a file
libft/ft_printf/print_addr_helper.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_addr_helper.c.s
.PHONY : libft/ft_printf/print_addr_helper.c.s

libft/ft_printf/print_chars_helper.o: libft/ft_printf/print_chars_helper.c.o

.PHONY : libft/ft_printf/print_chars_helper.o

# target to build an object file
libft/ft_printf/print_chars_helper.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_chars_helper.c.o
.PHONY : libft/ft_printf/print_chars_helper.c.o

libft/ft_printf/print_chars_helper.i: libft/ft_printf/print_chars_helper.c.i

.PHONY : libft/ft_printf/print_chars_helper.i

# target to preprocess a source file
libft/ft_printf/print_chars_helper.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_chars_helper.c.i
.PHONY : libft/ft_printf/print_chars_helper.c.i

libft/ft_printf/print_chars_helper.s: libft/ft_printf/print_chars_helper.c.s

.PHONY : libft/ft_printf/print_chars_helper.s

# target to generate assembly for a file
libft/ft_printf/print_chars_helper.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_chars_helper.c.s
.PHONY : libft/ft_printf/print_chars_helper.c.s

libft/ft_printf/print_float.o: libft/ft_printf/print_float.c.o

.PHONY : libft/ft_printf/print_float.o

# target to build an object file
libft/ft_printf/print_float.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_float.c.o
.PHONY : libft/ft_printf/print_float.c.o

libft/ft_printf/print_float.i: libft/ft_printf/print_float.c.i

.PHONY : libft/ft_printf/print_float.i

# target to preprocess a source file
libft/ft_printf/print_float.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_float.c.i
.PHONY : libft/ft_printf/print_float.c.i

libft/ft_printf/print_float.s: libft/ft_printf/print_float.c.s

.PHONY : libft/ft_printf/print_float.s

# target to generate assembly for a file
libft/ft_printf/print_float.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_float.c.s
.PHONY : libft/ft_printf/print_float.c.s

libft/ft_printf/print_float2.o: libft/ft_printf/print_float2.c.o

.PHONY : libft/ft_printf/print_float2.o

# target to build an object file
libft/ft_printf/print_float2.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_float2.c.o
.PHONY : libft/ft_printf/print_float2.c.o

libft/ft_printf/print_float2.i: libft/ft_printf/print_float2.c.i

.PHONY : libft/ft_printf/print_float2.i

# target to preprocess a source file
libft/ft_printf/print_float2.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_float2.c.i
.PHONY : libft/ft_printf/print_float2.c.i

libft/ft_printf/print_float2.s: libft/ft_printf/print_float2.c.s

.PHONY : libft/ft_printf/print_float2.s

# target to generate assembly for a file
libft/ft_printf/print_float2.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_float2.c.s
.PHONY : libft/ft_printf/print_float2.c.s

libft/ft_printf/print_ints_helper.o: libft/ft_printf/print_ints_helper.c.o

.PHONY : libft/ft_printf/print_ints_helper.o

# target to build an object file
libft/ft_printf/print_ints_helper.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_ints_helper.c.o
.PHONY : libft/ft_printf/print_ints_helper.c.o

libft/ft_printf/print_ints_helper.i: libft/ft_printf/print_ints_helper.c.i

.PHONY : libft/ft_printf/print_ints_helper.i

# target to preprocess a source file
libft/ft_printf/print_ints_helper.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_ints_helper.c.i
.PHONY : libft/ft_printf/print_ints_helper.c.i

libft/ft_printf/print_ints_helper.s: libft/ft_printf/print_ints_helper.c.s

.PHONY : libft/ft_printf/print_ints_helper.s

# target to generate assembly for a file
libft/ft_printf/print_ints_helper.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_ints_helper.c.s
.PHONY : libft/ft_printf/print_ints_helper.c.s

libft/ft_printf/print_percent_helper.o: libft/ft_printf/print_percent_helper.c.o

.PHONY : libft/ft_printf/print_percent_helper.o

# target to build an object file
libft/ft_printf/print_percent_helper.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_percent_helper.c.o
.PHONY : libft/ft_printf/print_percent_helper.c.o

libft/ft_printf/print_percent_helper.i: libft/ft_printf/print_percent_helper.c.i

.PHONY : libft/ft_printf/print_percent_helper.i

# target to preprocess a source file
libft/ft_printf/print_percent_helper.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_percent_helper.c.i
.PHONY : libft/ft_printf/print_percent_helper.c.i

libft/ft_printf/print_percent_helper.s: libft/ft_printf/print_percent_helper.c.s

.PHONY : libft/ft_printf/print_percent_helper.s

# target to generate assembly for a file
libft/ft_printf/print_percent_helper.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_percent_helper.c.s
.PHONY : libft/ft_printf/print_percent_helper.c.s

libft/ft_printf/print_uns_helper.o: libft/ft_printf/print_uns_helper.c.o

.PHONY : libft/ft_printf/print_uns_helper.o

# target to build an object file
libft/ft_printf/print_uns_helper.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_uns_helper.c.o
.PHONY : libft/ft_printf/print_uns_helper.c.o

libft/ft_printf/print_uns_helper.i: libft/ft_printf/print_uns_helper.c.i

.PHONY : libft/ft_printf/print_uns_helper.i

# target to preprocess a source file
libft/ft_printf/print_uns_helper.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_uns_helper.c.i
.PHONY : libft/ft_printf/print_uns_helper.c.i

libft/ft_printf/print_uns_helper.s: libft/ft_printf/print_uns_helper.c.s

.PHONY : libft/ft_printf/print_uns_helper.s

# target to generate assembly for a file
libft/ft_printf/print_uns_helper.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_printf/print_uns_helper.c.s
.PHONY : libft/ft_printf/print_uns_helper.c.s

libft/ft_putchar.o: libft/ft_putchar.c.o

.PHONY : libft/ft_putchar.o

# target to build an object file
libft/ft_putchar.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putchar.c.o
.PHONY : libft/ft_putchar.c.o

libft/ft_putchar.i: libft/ft_putchar.c.i

.PHONY : libft/ft_putchar.i

# target to preprocess a source file
libft/ft_putchar.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putchar.c.i
.PHONY : libft/ft_putchar.c.i

libft/ft_putchar.s: libft/ft_putchar.c.s

.PHONY : libft/ft_putchar.s

# target to generate assembly for a file
libft/ft_putchar.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putchar.c.s
.PHONY : libft/ft_putchar.c.s

libft/ft_putchar_fd.o: libft/ft_putchar_fd.c.o

.PHONY : libft/ft_putchar_fd.o

# target to build an object file
libft/ft_putchar_fd.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putchar_fd.c.o
.PHONY : libft/ft_putchar_fd.c.o

libft/ft_putchar_fd.i: libft/ft_putchar_fd.c.i

.PHONY : libft/ft_putchar_fd.i

# target to preprocess a source file
libft/ft_putchar_fd.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putchar_fd.c.i
.PHONY : libft/ft_putchar_fd.c.i

libft/ft_putchar_fd.s: libft/ft_putchar_fd.c.s

.PHONY : libft/ft_putchar_fd.s

# target to generate assembly for a file
libft/ft_putchar_fd.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putchar_fd.c.s
.PHONY : libft/ft_putchar_fd.c.s

libft/ft_putendl.o: libft/ft_putendl.c.o

.PHONY : libft/ft_putendl.o

# target to build an object file
libft/ft_putendl.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putendl.c.o
.PHONY : libft/ft_putendl.c.o

libft/ft_putendl.i: libft/ft_putendl.c.i

.PHONY : libft/ft_putendl.i

# target to preprocess a source file
libft/ft_putendl.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putendl.c.i
.PHONY : libft/ft_putendl.c.i

libft/ft_putendl.s: libft/ft_putendl.c.s

.PHONY : libft/ft_putendl.s

# target to generate assembly for a file
libft/ft_putendl.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putendl.c.s
.PHONY : libft/ft_putendl.c.s

libft/ft_putendl_fd.o: libft/ft_putendl_fd.c.o

.PHONY : libft/ft_putendl_fd.o

# target to build an object file
libft/ft_putendl_fd.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putendl_fd.c.o
.PHONY : libft/ft_putendl_fd.c.o

libft/ft_putendl_fd.i: libft/ft_putendl_fd.c.i

.PHONY : libft/ft_putendl_fd.i

# target to preprocess a source file
libft/ft_putendl_fd.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putendl_fd.c.i
.PHONY : libft/ft_putendl_fd.c.i

libft/ft_putendl_fd.s: libft/ft_putendl_fd.c.s

.PHONY : libft/ft_putendl_fd.s

# target to generate assembly for a file
libft/ft_putendl_fd.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putendl_fd.c.s
.PHONY : libft/ft_putendl_fd.c.s

libft/ft_putnbr.o: libft/ft_putnbr.c.o

.PHONY : libft/ft_putnbr.o

# target to build an object file
libft/ft_putnbr.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putnbr.c.o
.PHONY : libft/ft_putnbr.c.o

libft/ft_putnbr.i: libft/ft_putnbr.c.i

.PHONY : libft/ft_putnbr.i

# target to preprocess a source file
libft/ft_putnbr.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putnbr.c.i
.PHONY : libft/ft_putnbr.c.i

libft/ft_putnbr.s: libft/ft_putnbr.c.s

.PHONY : libft/ft_putnbr.s

# target to generate assembly for a file
libft/ft_putnbr.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putnbr.c.s
.PHONY : libft/ft_putnbr.c.s

libft/ft_putnbr_fd.o: libft/ft_putnbr_fd.c.o

.PHONY : libft/ft_putnbr_fd.o

# target to build an object file
libft/ft_putnbr_fd.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putnbr_fd.c.o
.PHONY : libft/ft_putnbr_fd.c.o

libft/ft_putnbr_fd.i: libft/ft_putnbr_fd.c.i

.PHONY : libft/ft_putnbr_fd.i

# target to preprocess a source file
libft/ft_putnbr_fd.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putnbr_fd.c.i
.PHONY : libft/ft_putnbr_fd.c.i

libft/ft_putnbr_fd.s: libft/ft_putnbr_fd.c.s

.PHONY : libft/ft_putnbr_fd.s

# target to generate assembly for a file
libft/ft_putnbr_fd.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putnbr_fd.c.s
.PHONY : libft/ft_putnbr_fd.c.s

libft/ft_putstr.o: libft/ft_putstr.c.o

.PHONY : libft/ft_putstr.o

# target to build an object file
libft/ft_putstr.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putstr.c.o
.PHONY : libft/ft_putstr.c.o

libft/ft_putstr.i: libft/ft_putstr.c.i

.PHONY : libft/ft_putstr.i

# target to preprocess a source file
libft/ft_putstr.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putstr.c.i
.PHONY : libft/ft_putstr.c.i

libft/ft_putstr.s: libft/ft_putstr.c.s

.PHONY : libft/ft_putstr.s

# target to generate assembly for a file
libft/ft_putstr.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putstr.c.s
.PHONY : libft/ft_putstr.c.s

libft/ft_putstr_fd.o: libft/ft_putstr_fd.c.o

.PHONY : libft/ft_putstr_fd.o

# target to build an object file
libft/ft_putstr_fd.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putstr_fd.c.o
.PHONY : libft/ft_putstr_fd.c.o

libft/ft_putstr_fd.i: libft/ft_putstr_fd.c.i

.PHONY : libft/ft_putstr_fd.i

# target to preprocess a source file
libft/ft_putstr_fd.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putstr_fd.c.i
.PHONY : libft/ft_putstr_fd.c.i

libft/ft_putstr_fd.s: libft/ft_putstr_fd.c.s

.PHONY : libft/ft_putstr_fd.s

# target to generate assembly for a file
libft/ft_putstr_fd.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_putstr_fd.c.s
.PHONY : libft/ft_putstr_fd.c.s

libft/ft_range.o: libft/ft_range.c.o

.PHONY : libft/ft_range.o

# target to build an object file
libft/ft_range.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_range.c.o
.PHONY : libft/ft_range.c.o

libft/ft_range.i: libft/ft_range.c.i

.PHONY : libft/ft_range.i

# target to preprocess a source file
libft/ft_range.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_range.c.i
.PHONY : libft/ft_range.c.i

libft/ft_range.s: libft/ft_range.c.s

.PHONY : libft/ft_range.s

# target to generate assembly for a file
libft/ft_range.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_range.c.s
.PHONY : libft/ft_range.c.s

libft/ft_remove_sstr.o: libft/ft_remove_sstr.c.o

.PHONY : libft/ft_remove_sstr.o

# target to build an object file
libft/ft_remove_sstr.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_remove_sstr.c.o
.PHONY : libft/ft_remove_sstr.c.o

libft/ft_remove_sstr.i: libft/ft_remove_sstr.c.i

.PHONY : libft/ft_remove_sstr.i

# target to preprocess a source file
libft/ft_remove_sstr.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_remove_sstr.c.i
.PHONY : libft/ft_remove_sstr.c.i

libft/ft_remove_sstr.s: libft/ft_remove_sstr.c.s

.PHONY : libft/ft_remove_sstr.s

# target to generate assembly for a file
libft/ft_remove_sstr.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_remove_sstr.c.s
.PHONY : libft/ft_remove_sstr.c.s

libft/ft_strcat.o: libft/ft_strcat.c.o

.PHONY : libft/ft_strcat.o

# target to build an object file
libft/ft_strcat.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strcat.c.o
.PHONY : libft/ft_strcat.c.o

libft/ft_strcat.i: libft/ft_strcat.c.i

.PHONY : libft/ft_strcat.i

# target to preprocess a source file
libft/ft_strcat.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strcat.c.i
.PHONY : libft/ft_strcat.c.i

libft/ft_strcat.s: libft/ft_strcat.c.s

.PHONY : libft/ft_strcat.s

# target to generate assembly for a file
libft/ft_strcat.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strcat.c.s
.PHONY : libft/ft_strcat.c.s

libft/ft_strchr.o: libft/ft_strchr.c.o

.PHONY : libft/ft_strchr.o

# target to build an object file
libft/ft_strchr.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strchr.c.o
.PHONY : libft/ft_strchr.c.o

libft/ft_strchr.i: libft/ft_strchr.c.i

.PHONY : libft/ft_strchr.i

# target to preprocess a source file
libft/ft_strchr.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strchr.c.i
.PHONY : libft/ft_strchr.c.i

libft/ft_strchr.s: libft/ft_strchr.c.s

.PHONY : libft/ft_strchr.s

# target to generate assembly for a file
libft/ft_strchr.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strchr.c.s
.PHONY : libft/ft_strchr.c.s

libft/ft_strclr.o: libft/ft_strclr.c.o

.PHONY : libft/ft_strclr.o

# target to build an object file
libft/ft_strclr.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strclr.c.o
.PHONY : libft/ft_strclr.c.o

libft/ft_strclr.i: libft/ft_strclr.c.i

.PHONY : libft/ft_strclr.i

# target to preprocess a source file
libft/ft_strclr.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strclr.c.i
.PHONY : libft/ft_strclr.c.i

libft/ft_strclr.s: libft/ft_strclr.c.s

.PHONY : libft/ft_strclr.s

# target to generate assembly for a file
libft/ft_strclr.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strclr.c.s
.PHONY : libft/ft_strclr.c.s

libft/ft_strcmp.o: libft/ft_strcmp.c.o

.PHONY : libft/ft_strcmp.o

# target to build an object file
libft/ft_strcmp.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strcmp.c.o
.PHONY : libft/ft_strcmp.c.o

libft/ft_strcmp.i: libft/ft_strcmp.c.i

.PHONY : libft/ft_strcmp.i

# target to preprocess a source file
libft/ft_strcmp.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strcmp.c.i
.PHONY : libft/ft_strcmp.c.i

libft/ft_strcmp.s: libft/ft_strcmp.c.s

.PHONY : libft/ft_strcmp.s

# target to generate assembly for a file
libft/ft_strcmp.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strcmp.c.s
.PHONY : libft/ft_strcmp.c.s

libft/ft_strcpy.o: libft/ft_strcpy.c.o

.PHONY : libft/ft_strcpy.o

# target to build an object file
libft/ft_strcpy.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strcpy.c.o
.PHONY : libft/ft_strcpy.c.o

libft/ft_strcpy.i: libft/ft_strcpy.c.i

.PHONY : libft/ft_strcpy.i

# target to preprocess a source file
libft/ft_strcpy.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strcpy.c.i
.PHONY : libft/ft_strcpy.c.i

libft/ft_strcpy.s: libft/ft_strcpy.c.s

.PHONY : libft/ft_strcpy.s

# target to generate assembly for a file
libft/ft_strcpy.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strcpy.c.s
.PHONY : libft/ft_strcpy.c.s

libft/ft_strdel.o: libft/ft_strdel.c.o

.PHONY : libft/ft_strdel.o

# target to build an object file
libft/ft_strdel.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strdel.c.o
.PHONY : libft/ft_strdel.c.o

libft/ft_strdel.i: libft/ft_strdel.c.i

.PHONY : libft/ft_strdel.i

# target to preprocess a source file
libft/ft_strdel.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strdel.c.i
.PHONY : libft/ft_strdel.c.i

libft/ft_strdel.s: libft/ft_strdel.c.s

.PHONY : libft/ft_strdel.s

# target to generate assembly for a file
libft/ft_strdel.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strdel.c.s
.PHONY : libft/ft_strdel.c.s

libft/ft_strdup.o: libft/ft_strdup.c.o

.PHONY : libft/ft_strdup.o

# target to build an object file
libft/ft_strdup.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strdup.c.o
.PHONY : libft/ft_strdup.c.o

libft/ft_strdup.i: libft/ft_strdup.c.i

.PHONY : libft/ft_strdup.i

# target to preprocess a source file
libft/ft_strdup.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strdup.c.i
.PHONY : libft/ft_strdup.c.i

libft/ft_strdup.s: libft/ft_strdup.c.s

.PHONY : libft/ft_strdup.s

# target to generate assembly for a file
libft/ft_strdup.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strdup.c.s
.PHONY : libft/ft_strdup.c.s

libft/ft_strequ.o: libft/ft_strequ.c.o

.PHONY : libft/ft_strequ.o

# target to build an object file
libft/ft_strequ.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strequ.c.o
.PHONY : libft/ft_strequ.c.o

libft/ft_strequ.i: libft/ft_strequ.c.i

.PHONY : libft/ft_strequ.i

# target to preprocess a source file
libft/ft_strequ.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strequ.c.i
.PHONY : libft/ft_strequ.c.i

libft/ft_strequ.s: libft/ft_strequ.c.s

.PHONY : libft/ft_strequ.s

# target to generate assembly for a file
libft/ft_strequ.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strequ.c.s
.PHONY : libft/ft_strequ.c.s

libft/ft_striter.o: libft/ft_striter.c.o

.PHONY : libft/ft_striter.o

# target to build an object file
libft/ft_striter.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_striter.c.o
.PHONY : libft/ft_striter.c.o

libft/ft_striter.i: libft/ft_striter.c.i

.PHONY : libft/ft_striter.i

# target to preprocess a source file
libft/ft_striter.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_striter.c.i
.PHONY : libft/ft_striter.c.i

libft/ft_striter.s: libft/ft_striter.c.s

.PHONY : libft/ft_striter.s

# target to generate assembly for a file
libft/ft_striter.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_striter.c.s
.PHONY : libft/ft_striter.c.s

libft/ft_striteri.o: libft/ft_striteri.c.o

.PHONY : libft/ft_striteri.o

# target to build an object file
libft/ft_striteri.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_striteri.c.o
.PHONY : libft/ft_striteri.c.o

libft/ft_striteri.i: libft/ft_striteri.c.i

.PHONY : libft/ft_striteri.i

# target to preprocess a source file
libft/ft_striteri.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_striteri.c.i
.PHONY : libft/ft_striteri.c.i

libft/ft_striteri.s: libft/ft_striteri.c.s

.PHONY : libft/ft_striteri.s

# target to generate assembly for a file
libft/ft_striteri.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_striteri.c.s
.PHONY : libft/ft_striteri.c.s

libft/ft_strjoin.o: libft/ft_strjoin.c.o

.PHONY : libft/ft_strjoin.o

# target to build an object file
libft/ft_strjoin.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strjoin.c.o
.PHONY : libft/ft_strjoin.c.o

libft/ft_strjoin.i: libft/ft_strjoin.c.i

.PHONY : libft/ft_strjoin.i

# target to preprocess a source file
libft/ft_strjoin.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strjoin.c.i
.PHONY : libft/ft_strjoin.c.i

libft/ft_strjoin.s: libft/ft_strjoin.c.s

.PHONY : libft/ft_strjoin.s

# target to generate assembly for a file
libft/ft_strjoin.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strjoin.c.s
.PHONY : libft/ft_strjoin.c.s

libft/ft_strlcat.o: libft/ft_strlcat.c.o

.PHONY : libft/ft_strlcat.o

# target to build an object file
libft/ft_strlcat.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strlcat.c.o
.PHONY : libft/ft_strlcat.c.o

libft/ft_strlcat.i: libft/ft_strlcat.c.i

.PHONY : libft/ft_strlcat.i

# target to preprocess a source file
libft/ft_strlcat.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strlcat.c.i
.PHONY : libft/ft_strlcat.c.i

libft/ft_strlcat.s: libft/ft_strlcat.c.s

.PHONY : libft/ft_strlcat.s

# target to generate assembly for a file
libft/ft_strlcat.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strlcat.c.s
.PHONY : libft/ft_strlcat.c.s

libft/ft_strlen.o: libft/ft_strlen.c.o

.PHONY : libft/ft_strlen.o

# target to build an object file
libft/ft_strlen.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strlen.c.o
.PHONY : libft/ft_strlen.c.o

libft/ft_strlen.i: libft/ft_strlen.c.i

.PHONY : libft/ft_strlen.i

# target to preprocess a source file
libft/ft_strlen.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strlen.c.i
.PHONY : libft/ft_strlen.c.i

libft/ft_strlen.s: libft/ft_strlen.c.s

.PHONY : libft/ft_strlen.s

# target to generate assembly for a file
libft/ft_strlen.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strlen.c.s
.PHONY : libft/ft_strlen.c.s

libft/ft_strmap.o: libft/ft_strmap.c.o

.PHONY : libft/ft_strmap.o

# target to build an object file
libft/ft_strmap.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strmap.c.o
.PHONY : libft/ft_strmap.c.o

libft/ft_strmap.i: libft/ft_strmap.c.i

.PHONY : libft/ft_strmap.i

# target to preprocess a source file
libft/ft_strmap.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strmap.c.i
.PHONY : libft/ft_strmap.c.i

libft/ft_strmap.s: libft/ft_strmap.c.s

.PHONY : libft/ft_strmap.s

# target to generate assembly for a file
libft/ft_strmap.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strmap.c.s
.PHONY : libft/ft_strmap.c.s

libft/ft_strmapi.o: libft/ft_strmapi.c.o

.PHONY : libft/ft_strmapi.o

# target to build an object file
libft/ft_strmapi.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strmapi.c.o
.PHONY : libft/ft_strmapi.c.o

libft/ft_strmapi.i: libft/ft_strmapi.c.i

.PHONY : libft/ft_strmapi.i

# target to preprocess a source file
libft/ft_strmapi.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strmapi.c.i
.PHONY : libft/ft_strmapi.c.i

libft/ft_strmapi.s: libft/ft_strmapi.c.s

.PHONY : libft/ft_strmapi.s

# target to generate assembly for a file
libft/ft_strmapi.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strmapi.c.s
.PHONY : libft/ft_strmapi.c.s

libft/ft_strncat.o: libft/ft_strncat.c.o

.PHONY : libft/ft_strncat.o

# target to build an object file
libft/ft_strncat.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strncat.c.o
.PHONY : libft/ft_strncat.c.o

libft/ft_strncat.i: libft/ft_strncat.c.i

.PHONY : libft/ft_strncat.i

# target to preprocess a source file
libft/ft_strncat.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strncat.c.i
.PHONY : libft/ft_strncat.c.i

libft/ft_strncat.s: libft/ft_strncat.c.s

.PHONY : libft/ft_strncat.s

# target to generate assembly for a file
libft/ft_strncat.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strncat.c.s
.PHONY : libft/ft_strncat.c.s

libft/ft_strncmp.o: libft/ft_strncmp.c.o

.PHONY : libft/ft_strncmp.o

# target to build an object file
libft/ft_strncmp.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strncmp.c.o
.PHONY : libft/ft_strncmp.c.o

libft/ft_strncmp.i: libft/ft_strncmp.c.i

.PHONY : libft/ft_strncmp.i

# target to preprocess a source file
libft/ft_strncmp.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strncmp.c.i
.PHONY : libft/ft_strncmp.c.i

libft/ft_strncmp.s: libft/ft_strncmp.c.s

.PHONY : libft/ft_strncmp.s

# target to generate assembly for a file
libft/ft_strncmp.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strncmp.c.s
.PHONY : libft/ft_strncmp.c.s

libft/ft_strncpy.o: libft/ft_strncpy.c.o

.PHONY : libft/ft_strncpy.o

# target to build an object file
libft/ft_strncpy.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strncpy.c.o
.PHONY : libft/ft_strncpy.c.o

libft/ft_strncpy.i: libft/ft_strncpy.c.i

.PHONY : libft/ft_strncpy.i

# target to preprocess a source file
libft/ft_strncpy.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strncpy.c.i
.PHONY : libft/ft_strncpy.c.i

libft/ft_strncpy.s: libft/ft_strncpy.c.s

.PHONY : libft/ft_strncpy.s

# target to generate assembly for a file
libft/ft_strncpy.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strncpy.c.s
.PHONY : libft/ft_strncpy.c.s

libft/ft_strnequ.o: libft/ft_strnequ.c.o

.PHONY : libft/ft_strnequ.o

# target to build an object file
libft/ft_strnequ.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strnequ.c.o
.PHONY : libft/ft_strnequ.c.o

libft/ft_strnequ.i: libft/ft_strnequ.c.i

.PHONY : libft/ft_strnequ.i

# target to preprocess a source file
libft/ft_strnequ.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strnequ.c.i
.PHONY : libft/ft_strnequ.c.i

libft/ft_strnequ.s: libft/ft_strnequ.c.s

.PHONY : libft/ft_strnequ.s

# target to generate assembly for a file
libft/ft_strnequ.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strnequ.c.s
.PHONY : libft/ft_strnequ.c.s

libft/ft_strnew.o: libft/ft_strnew.c.o

.PHONY : libft/ft_strnew.o

# target to build an object file
libft/ft_strnew.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strnew.c.o
.PHONY : libft/ft_strnew.c.o

libft/ft_strnew.i: libft/ft_strnew.c.i

.PHONY : libft/ft_strnew.i

# target to preprocess a source file
libft/ft_strnew.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strnew.c.i
.PHONY : libft/ft_strnew.c.i

libft/ft_strnew.s: libft/ft_strnew.c.s

.PHONY : libft/ft_strnew.s

# target to generate assembly for a file
libft/ft_strnew.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strnew.c.s
.PHONY : libft/ft_strnew.c.s

libft/ft_strnstr.o: libft/ft_strnstr.c.o

.PHONY : libft/ft_strnstr.o

# target to build an object file
libft/ft_strnstr.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strnstr.c.o
.PHONY : libft/ft_strnstr.c.o

libft/ft_strnstr.i: libft/ft_strnstr.c.i

.PHONY : libft/ft_strnstr.i

# target to preprocess a source file
libft/ft_strnstr.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strnstr.c.i
.PHONY : libft/ft_strnstr.c.i

libft/ft_strnstr.s: libft/ft_strnstr.c.s

.PHONY : libft/ft_strnstr.s

# target to generate assembly for a file
libft/ft_strnstr.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strnstr.c.s
.PHONY : libft/ft_strnstr.c.s

libft/ft_strrchr.o: libft/ft_strrchr.c.o

.PHONY : libft/ft_strrchr.o

# target to build an object file
libft/ft_strrchr.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strrchr.c.o
.PHONY : libft/ft_strrchr.c.o

libft/ft_strrchr.i: libft/ft_strrchr.c.i

.PHONY : libft/ft_strrchr.i

# target to preprocess a source file
libft/ft_strrchr.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strrchr.c.i
.PHONY : libft/ft_strrchr.c.i

libft/ft_strrchr.s: libft/ft_strrchr.c.s

.PHONY : libft/ft_strrchr.s

# target to generate assembly for a file
libft/ft_strrchr.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strrchr.c.s
.PHONY : libft/ft_strrchr.c.s

libft/ft_strrev.o: libft/ft_strrev.c.o

.PHONY : libft/ft_strrev.o

# target to build an object file
libft/ft_strrev.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strrev.c.o
.PHONY : libft/ft_strrev.c.o

libft/ft_strrev.i: libft/ft_strrev.c.i

.PHONY : libft/ft_strrev.i

# target to preprocess a source file
libft/ft_strrev.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strrev.c.i
.PHONY : libft/ft_strrev.c.i

libft/ft_strrev.s: libft/ft_strrev.c.s

.PHONY : libft/ft_strrev.s

# target to generate assembly for a file
libft/ft_strrev.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strrev.c.s
.PHONY : libft/ft_strrev.c.s

libft/ft_strsplit.o: libft/ft_strsplit.c.o

.PHONY : libft/ft_strsplit.o

# target to build an object file
libft/ft_strsplit.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strsplit.c.o
.PHONY : libft/ft_strsplit.c.o

libft/ft_strsplit.i: libft/ft_strsplit.c.i

.PHONY : libft/ft_strsplit.i

# target to preprocess a source file
libft/ft_strsplit.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strsplit.c.i
.PHONY : libft/ft_strsplit.c.i

libft/ft_strsplit.s: libft/ft_strsplit.c.s

.PHONY : libft/ft_strsplit.s

# target to generate assembly for a file
libft/ft_strsplit.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strsplit.c.s
.PHONY : libft/ft_strsplit.c.s

libft/ft_strstr.o: libft/ft_strstr.c.o

.PHONY : libft/ft_strstr.o

# target to build an object file
libft/ft_strstr.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strstr.c.o
.PHONY : libft/ft_strstr.c.o

libft/ft_strstr.i: libft/ft_strstr.c.i

.PHONY : libft/ft_strstr.i

# target to preprocess a source file
libft/ft_strstr.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strstr.c.i
.PHONY : libft/ft_strstr.c.i

libft/ft_strstr.s: libft/ft_strstr.c.s

.PHONY : libft/ft_strstr.s

# target to generate assembly for a file
libft/ft_strstr.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strstr.c.s
.PHONY : libft/ft_strstr.c.s

libft/ft_strsub.o: libft/ft_strsub.c.o

.PHONY : libft/ft_strsub.o

# target to build an object file
libft/ft_strsub.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strsub.c.o
.PHONY : libft/ft_strsub.c.o

libft/ft_strsub.i: libft/ft_strsub.c.i

.PHONY : libft/ft_strsub.i

# target to preprocess a source file
libft/ft_strsub.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strsub.c.i
.PHONY : libft/ft_strsub.c.i

libft/ft_strsub.s: libft/ft_strsub.c.s

.PHONY : libft/ft_strsub.s

# target to generate assembly for a file
libft/ft_strsub.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strsub.c.s
.PHONY : libft/ft_strsub.c.s

libft/ft_strtrim.o: libft/ft_strtrim.c.o

.PHONY : libft/ft_strtrim.o

# target to build an object file
libft/ft_strtrim.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strtrim.c.o
.PHONY : libft/ft_strtrim.c.o

libft/ft_strtrim.i: libft/ft_strtrim.c.i

.PHONY : libft/ft_strtrim.i

# target to preprocess a source file
libft/ft_strtrim.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strtrim.c.i
.PHONY : libft/ft_strtrim.c.i

libft/ft_strtrim.s: libft/ft_strtrim.c.s

.PHONY : libft/ft_strtrim.s

# target to generate assembly for a file
libft/ft_strtrim.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_strtrim.c.s
.PHONY : libft/ft_strtrim.c.s

libft/ft_tolower.o: libft/ft_tolower.c.o

.PHONY : libft/ft_tolower.o

# target to build an object file
libft/ft_tolower.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_tolower.c.o
.PHONY : libft/ft_tolower.c.o

libft/ft_tolower.i: libft/ft_tolower.c.i

.PHONY : libft/ft_tolower.i

# target to preprocess a source file
libft/ft_tolower.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_tolower.c.i
.PHONY : libft/ft_tolower.c.i

libft/ft_tolower.s: libft/ft_tolower.c.s

.PHONY : libft/ft_tolower.s

# target to generate assembly for a file
libft/ft_tolower.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_tolower.c.s
.PHONY : libft/ft_tolower.c.s

libft/ft_toupper.o: libft/ft_toupper.c.o

.PHONY : libft/ft_toupper.o

# target to build an object file
libft/ft_toupper.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_toupper.c.o
.PHONY : libft/ft_toupper.c.o

libft/ft_toupper.i: libft/ft_toupper.c.i

.PHONY : libft/ft_toupper.i

# target to preprocess a source file
libft/ft_toupper.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_toupper.c.i
.PHONY : libft/ft_toupper.c.i

libft/ft_toupper.s: libft/ft_toupper.c.s

.PHONY : libft/ft_toupper.s

# target to generate assembly for a file
libft/ft_toupper.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_toupper.c.s
.PHONY : libft/ft_toupper.c.s

libft/ft_wcount.o: libft/ft_wcount.c.o

.PHONY : libft/ft_wcount.o

# target to build an object file
libft/ft_wcount.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_wcount.c.o
.PHONY : libft/ft_wcount.c.o

libft/ft_wcount.i: libft/ft_wcount.c.i

.PHONY : libft/ft_wcount.i

# target to preprocess a source file
libft/ft_wcount.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_wcount.c.i
.PHONY : libft/ft_wcount.c.i

libft/ft_wcount.s: libft/ft_wcount.c.s

.PHONY : libft/ft_wcount.s

# target to generate assembly for a file
libft/ft_wcount.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/ft_wcount.c.s
.PHONY : libft/ft_wcount.c.s

libft/get_next_line.o: libft/get_next_line.c.o

.PHONY : libft/get_next_line.o

# target to build an object file
libft/get_next_line.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/get_next_line.c.o
.PHONY : libft/get_next_line.c.o

libft/get_next_line.i: libft/get_next_line.c.i

.PHONY : libft/get_next_line.i

# target to preprocess a source file
libft/get_next_line.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/get_next_line.c.i
.PHONY : libft/get_next_line.c.i

libft/get_next_line.s: libft/get_next_line.c.s

.PHONY : libft/get_next_line.s

# target to generate assembly for a file
libft/get_next_line.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/libft/get_next_line.c.s
.PHONY : libft/get_next_line.c.s

ls_with_l.o: ls_with_l.c.o

.PHONY : ls_with_l.o

# target to build an object file
ls_with_l.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/ls_with_l.c.o
.PHONY : ls_with_l.c.o

ls_with_l.i: ls_with_l.c.i

.PHONY : ls_with_l.i

# target to preprocess a source file
ls_with_l.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/ls_with_l.c.i
.PHONY : ls_with_l.c.i

ls_with_l.s: ls_with_l.c.s

.PHONY : ls_with_l.s

# target to generate assembly for a file
ls_with_l.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/ls_with_l.c.s
.PHONY : ls_with_l.c.s

ls_without_l.o: ls_without_l.c.o

.PHONY : ls_without_l.o

# target to build an object file
ls_without_l.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/ls_without_l.c.o
.PHONY : ls_without_l.c.o

ls_without_l.i: ls_without_l.c.i

.PHONY : ls_without_l.i

# target to preprocess a source file
ls_without_l.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/ls_without_l.c.i
.PHONY : ls_without_l.c.i

ls_without_l.s: ls_without_l.c.s

.PHONY : ls_without_l.s

# target to generate assembly for a file
ls_without_l.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/ls_without_l.c.s
.PHONY : ls_without_l.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/main.c.s
.PHONY : main.c.s

rec_flag_helper.o: rec_flag_helper.c.o

.PHONY : rec_flag_helper.o

# target to build an object file
rec_flag_helper.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/rec_flag_helper.c.o
.PHONY : rec_flag_helper.c.o

rec_flag_helper.i: rec_flag_helper.c.i

.PHONY : rec_flag_helper.i

# target to preprocess a source file
rec_flag_helper.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/rec_flag_helper.c.i
.PHONY : rec_flag_helper.c.i

rec_flag_helper.s: rec_flag_helper.c.s

.PHONY : rec_flag_helper.s

# target to generate assembly for a file
rec_flag_helper.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/rec_flag_helper.c.s
.PHONY : rec_flag_helper.c.s

t_file_helper.o: t_file_helper.c.o

.PHONY : t_file_helper.o

# target to build an object file
t_file_helper.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/t_file_helper.c.o
.PHONY : t_file_helper.c.o

t_file_helper.i: t_file_helper.c.i

.PHONY : t_file_helper.i

# target to preprocess a source file
t_file_helper.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/t_file_helper.c.i
.PHONY : t_file_helper.c.i

t_file_helper.s: t_file_helper.c.s

.PHONY : t_file_helper.s

# target to generate assembly for a file
t_file_helper.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/t_file_helper.c.s
.PHONY : t_file_helper.c.s

utils.o: utils.c.o

.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i

.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s

.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/utils.c.s
.PHONY : utils.c.s

utils2.o: utils2.c.o

.PHONY : utils2.o

# target to build an object file
utils2.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/utils2.c.o
.PHONY : utils2.c.o

utils2.i: utils2.c.i

.PHONY : utils2.i

# target to preprocess a source file
utils2.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/utils2.c.i
.PHONY : utils2.c.i

utils2.s: utils2.c.s

.PHONY : utils2.s

# target to generate assembly for a file
utils2.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/utils2.c.s
.PHONY : utils2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ft_ls"
	@echo "... acrights_helper.o"
	@echo "... acrights_helper.i"
	@echo "... acrights_helper.s"
	@echo "... arg_parser.o"
	@echo "... arg_parser.i"
	@echo "... arg_parser.s"
	@echo "... comparators.o"
	@echo "... comparators.i"
	@echo "... comparators.s"
	@echo "... comparators_2.o"
	@echo "... comparators_2.i"
	@echo "... comparators_2.s"
	@echo "... del_from_lists.o"
	@echo "... del_from_lists.i"
	@echo "... del_from_lists.s"
	@echo "... errors.o"
	@echo "... errors.i"
	@echo "... errors.s"
	@echo "... get_fileinfo_1.o"
	@echo "... get_fileinfo_1.i"
	@echo "... get_fileinfo_1.s"
	@echo "... get_fileinfo_2.o"
	@echo "... get_fileinfo_2.i"
	@echo "... get_fileinfo_2.s"
	@echo "... l_flag_helper1.o"
	@echo "... l_flag_helper1.i"
	@echo "... l_flag_helper1.s"
	@echo "... libft/ft_atoi.o"
	@echo "... libft/ft_atoi.i"
	@echo "... libft/ft_atoi.s"
	@echo "... libft/ft_bzero.o"
	@echo "... libft/ft_bzero.i"
	@echo "... libft/ft_bzero.s"
	@echo "... libft/ft_isalnum.o"
	@echo "... libft/ft_isalnum.i"
	@echo "... libft/ft_isalnum.s"
	@echo "... libft/ft_isalpha.o"
	@echo "... libft/ft_isalpha.i"
	@echo "... libft/ft_isalpha.s"
	@echo "... libft/ft_isascii.o"
	@echo "... libft/ft_isascii.i"
	@echo "... libft/ft_isascii.s"
	@echo "... libft/ft_isdigit.o"
	@echo "... libft/ft_isdigit.i"
	@echo "... libft/ft_isdigit.s"
	@echo "... libft/ft_isprint.o"
	@echo "... libft/ft_isprint.i"
	@echo "... libft/ft_isprint.s"
	@echo "... libft/ft_isspace.o"
	@echo "... libft/ft_isspace.i"
	@echo "... libft/ft_isspace.s"
	@echo "... libft/ft_itoa.o"
	@echo "... libft/ft_itoa.i"
	@echo "... libft/ft_itoa.s"
	@echo "... libft/ft_lstadd.o"
	@echo "... libft/ft_lstadd.i"
	@echo "... libft/ft_lstadd.s"
	@echo "... libft/ft_lstdel.o"
	@echo "... libft/ft_lstdel.i"
	@echo "... libft/ft_lstdel.s"
	@echo "... libft/ft_lstdelone.o"
	@echo "... libft/ft_lstdelone.i"
	@echo "... libft/ft_lstdelone.s"
	@echo "... libft/ft_lstiter.o"
	@echo "... libft/ft_lstiter.i"
	@echo "... libft/ft_lstiter.s"
	@echo "... libft/ft_lstmap.o"
	@echo "... libft/ft_lstmap.i"
	@echo "... libft/ft_lstmap.s"
	@echo "... libft/ft_lstnew.o"
	@echo "... libft/ft_lstnew.i"
	@echo "... libft/ft_lstnew.s"
	@echo "... libft/ft_memalloc.o"
	@echo "... libft/ft_memalloc.i"
	@echo "... libft/ft_memalloc.s"
	@echo "... libft/ft_memccpy.o"
	@echo "... libft/ft_memccpy.i"
	@echo "... libft/ft_memccpy.s"
	@echo "... libft/ft_memchr.o"
	@echo "... libft/ft_memchr.i"
	@echo "... libft/ft_memchr.s"
	@echo "... libft/ft_memcmp.o"
	@echo "... libft/ft_memcmp.i"
	@echo "... libft/ft_memcmp.s"
	@echo "... libft/ft_memcpy.o"
	@echo "... libft/ft_memcpy.i"
	@echo "... libft/ft_memcpy.s"
	@echo "... libft/ft_memdel.o"
	@echo "... libft/ft_memdel.i"
	@echo "... libft/ft_memdel.s"
	@echo "... libft/ft_memmove.o"
	@echo "... libft/ft_memmove.i"
	@echo "... libft/ft_memmove.s"
	@echo "... libft/ft_memset.o"
	@echo "... libft/ft_memset.i"
	@echo "... libft/ft_memset.s"
	@echo "... libft/ft_printf/colored.o"
	@echo "... libft/ft_printf/colored.i"
	@echo "... libft/ft_printf/colored.s"
	@echo "... libft/ft_printf/ft_itoa_base.o"
	@echo "... libft/ft_printf/ft_itoa_base.i"
	@echo "... libft/ft_printf/ft_itoa_base.s"
	@echo "... libft/ft_printf/ft_itoa_base_uns.o"
	@echo "... libft/ft_printf/ft_itoa_base_uns.i"
	@echo "... libft/ft_printf/ft_itoa_base_uns.s"
	@echo "... libft/ft_printf/ft_printf.o"
	@echo "... libft/ft_printf/ft_printf.i"
	@echo "... libft/ft_printf/ft_printf.s"
	@echo "... libft/ft_printf/get_format.o"
	@echo "... libft/ft_printf/get_format.i"
	@echo "... libft/ft_printf/get_format.s"
	@echo "... libft/ft_printf/helper_numbers.o"
	@echo "... libft/ft_printf/helper_numbers.i"
	@echo "... libft/ft_printf/helper_numbers.s"
	@echo "... libft/ft_printf/helper_numbers2.o"
	@echo "... libft/ft_printf/helper_numbers2.i"
	@echo "... libft/ft_printf/helper_numbers2.s"
	@echo "... libft/ft_printf/print_addr_helper.o"
	@echo "... libft/ft_printf/print_addr_helper.i"
	@echo "... libft/ft_printf/print_addr_helper.s"
	@echo "... libft/ft_printf/print_chars_helper.o"
	@echo "... libft/ft_printf/print_chars_helper.i"
	@echo "... libft/ft_printf/print_chars_helper.s"
	@echo "... libft/ft_printf/print_float.o"
	@echo "... libft/ft_printf/print_float.i"
	@echo "... libft/ft_printf/print_float.s"
	@echo "... libft/ft_printf/print_float2.o"
	@echo "... libft/ft_printf/print_float2.i"
	@echo "... libft/ft_printf/print_float2.s"
	@echo "... libft/ft_printf/print_ints_helper.o"
	@echo "... libft/ft_printf/print_ints_helper.i"
	@echo "... libft/ft_printf/print_ints_helper.s"
	@echo "... libft/ft_printf/print_percent_helper.o"
	@echo "... libft/ft_printf/print_percent_helper.i"
	@echo "... libft/ft_printf/print_percent_helper.s"
	@echo "... libft/ft_printf/print_uns_helper.o"
	@echo "... libft/ft_printf/print_uns_helper.i"
	@echo "... libft/ft_printf/print_uns_helper.s"
	@echo "... libft/ft_putchar.o"
	@echo "... libft/ft_putchar.i"
	@echo "... libft/ft_putchar.s"
	@echo "... libft/ft_putchar_fd.o"
	@echo "... libft/ft_putchar_fd.i"
	@echo "... libft/ft_putchar_fd.s"
	@echo "... libft/ft_putendl.o"
	@echo "... libft/ft_putendl.i"
	@echo "... libft/ft_putendl.s"
	@echo "... libft/ft_putendl_fd.o"
	@echo "... libft/ft_putendl_fd.i"
	@echo "... libft/ft_putendl_fd.s"
	@echo "... libft/ft_putnbr.o"
	@echo "... libft/ft_putnbr.i"
	@echo "... libft/ft_putnbr.s"
	@echo "... libft/ft_putnbr_fd.o"
	@echo "... libft/ft_putnbr_fd.i"
	@echo "... libft/ft_putnbr_fd.s"
	@echo "... libft/ft_putstr.o"
	@echo "... libft/ft_putstr.i"
	@echo "... libft/ft_putstr.s"
	@echo "... libft/ft_putstr_fd.o"
	@echo "... libft/ft_putstr_fd.i"
	@echo "... libft/ft_putstr_fd.s"
	@echo "... libft/ft_range.o"
	@echo "... libft/ft_range.i"
	@echo "... libft/ft_range.s"
	@echo "... libft/ft_remove_sstr.o"
	@echo "... libft/ft_remove_sstr.i"
	@echo "... libft/ft_remove_sstr.s"
	@echo "... libft/ft_strcat.o"
	@echo "... libft/ft_strcat.i"
	@echo "... libft/ft_strcat.s"
	@echo "... libft/ft_strchr.o"
	@echo "... libft/ft_strchr.i"
	@echo "... libft/ft_strchr.s"
	@echo "... libft/ft_strclr.o"
	@echo "... libft/ft_strclr.i"
	@echo "... libft/ft_strclr.s"
	@echo "... libft/ft_strcmp.o"
	@echo "... libft/ft_strcmp.i"
	@echo "... libft/ft_strcmp.s"
	@echo "... libft/ft_strcpy.o"
	@echo "... libft/ft_strcpy.i"
	@echo "... libft/ft_strcpy.s"
	@echo "... libft/ft_strdel.o"
	@echo "... libft/ft_strdel.i"
	@echo "... libft/ft_strdel.s"
	@echo "... libft/ft_strdup.o"
	@echo "... libft/ft_strdup.i"
	@echo "... libft/ft_strdup.s"
	@echo "... libft/ft_strequ.o"
	@echo "... libft/ft_strequ.i"
	@echo "... libft/ft_strequ.s"
	@echo "... libft/ft_striter.o"
	@echo "... libft/ft_striter.i"
	@echo "... libft/ft_striter.s"
	@echo "... libft/ft_striteri.o"
	@echo "... libft/ft_striteri.i"
	@echo "... libft/ft_striteri.s"
	@echo "... libft/ft_strjoin.o"
	@echo "... libft/ft_strjoin.i"
	@echo "... libft/ft_strjoin.s"
	@echo "... libft/ft_strlcat.o"
	@echo "... libft/ft_strlcat.i"
	@echo "... libft/ft_strlcat.s"
	@echo "... libft/ft_strlen.o"
	@echo "... libft/ft_strlen.i"
	@echo "... libft/ft_strlen.s"
	@echo "... libft/ft_strmap.o"
	@echo "... libft/ft_strmap.i"
	@echo "... libft/ft_strmap.s"
	@echo "... libft/ft_strmapi.o"
	@echo "... libft/ft_strmapi.i"
	@echo "... libft/ft_strmapi.s"
	@echo "... libft/ft_strncat.o"
	@echo "... libft/ft_strncat.i"
	@echo "... libft/ft_strncat.s"
	@echo "... libft/ft_strncmp.o"
	@echo "... libft/ft_strncmp.i"
	@echo "... libft/ft_strncmp.s"
	@echo "... libft/ft_strncpy.o"
	@echo "... libft/ft_strncpy.i"
	@echo "... libft/ft_strncpy.s"
	@echo "... libft/ft_strnequ.o"
	@echo "... libft/ft_strnequ.i"
	@echo "... libft/ft_strnequ.s"
	@echo "... libft/ft_strnew.o"
	@echo "... libft/ft_strnew.i"
	@echo "... libft/ft_strnew.s"
	@echo "... libft/ft_strnstr.o"
	@echo "... libft/ft_strnstr.i"
	@echo "... libft/ft_strnstr.s"
	@echo "... libft/ft_strrchr.o"
	@echo "... libft/ft_strrchr.i"
	@echo "... libft/ft_strrchr.s"
	@echo "... libft/ft_strrev.o"
	@echo "... libft/ft_strrev.i"
	@echo "... libft/ft_strrev.s"
	@echo "... libft/ft_strsplit.o"
	@echo "... libft/ft_strsplit.i"
	@echo "... libft/ft_strsplit.s"
	@echo "... libft/ft_strstr.o"
	@echo "... libft/ft_strstr.i"
	@echo "... libft/ft_strstr.s"
	@echo "... libft/ft_strsub.o"
	@echo "... libft/ft_strsub.i"
	@echo "... libft/ft_strsub.s"
	@echo "... libft/ft_strtrim.o"
	@echo "... libft/ft_strtrim.i"
	@echo "... libft/ft_strtrim.s"
	@echo "... libft/ft_tolower.o"
	@echo "... libft/ft_tolower.i"
	@echo "... libft/ft_tolower.s"
	@echo "... libft/ft_toupper.o"
	@echo "... libft/ft_toupper.i"
	@echo "... libft/ft_toupper.s"
	@echo "... libft/ft_wcount.o"
	@echo "... libft/ft_wcount.i"
	@echo "... libft/ft_wcount.s"
	@echo "... libft/get_next_line.o"
	@echo "... libft/get_next_line.i"
	@echo "... libft/get_next_line.s"
	@echo "... ls_with_l.o"
	@echo "... ls_with_l.i"
	@echo "... ls_with_l.s"
	@echo "... ls_without_l.o"
	@echo "... ls_without_l.i"
	@echo "... ls_without_l.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... rec_flag_helper.o"
	@echo "... rec_flag_helper.i"
	@echo "... rec_flag_helper.s"
	@echo "... t_file_helper.o"
	@echo "... t_file_helper.i"
	@echo "... t_file_helper.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... utils2.o"
	@echo "... utils2.i"
	@echo "... utils2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

